plugins {
    alias(libs.plugins.depman) apply false
}

allprojects {
    group = 'com.expenses'
    version = '0.1.0-SNAPSHOT'
}

subprojects {
    apply plugin: 'java'
    apply plugin: libs.plugins.depman.get().pluginId
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(libs.versions.java.get().toInteger())
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation libs.junit.jupiter
    }

    test {
        useJUnitPlatform()
    }
}
