plugins {
  alias(libs.plugins.depman)
}

allprojects {
  group = 'com.expenses'
  version = '0.1.0-SNAPSHOT'
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'io.spring.dependency-management'

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }

  repositories {
    mavenCentral()
  }

  dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
  }

  test {
    useJUnitPlatform()
  }
}
