plugins {
  alias(libs.plugins.depman)
}

allprojects {
  group = 'com.expenses'
  version = '0.1.0-SNAPSHOT'
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'io.spring.dependency-management'

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(libs.versions.java.get().toInteger())
    }
  }

  repositories {
    mavenCentral()
  // Apply org.apache.commons:commons-lang3 version override across all subprojects
  dependencyManagement {
    dependencies {
      dependency 'org.apache.commons:commons-lang3:3.17.0'
    }
  }

  }

  dependencies {
    testImplementation libs.junit.jupiter
  }

  test {
    useJUnitPlatform()
  }
}
