package com.expenses.svcsettle.service;

import java.util.UUID;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.expenses.svcsettle.dto.SettlementDto;
import com.expenses.svcsettle.entity.SettlementHistory;
import com.expenses.svcsettle.entity.SettlementPayment;
import com.expenses.svcsettle.entity.SettlementProposal;
import com.expenses.svcsettle.repository.SettlementHistoryRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class SettlementHistoryService {

  private final SettlementHistoryRepository settlementHistoryRepository;

  /**
   * Record settlement proposal creation
   */
  public void recordProposalCreated(SettlementProposal proposal, UUID userId) {
    SettlementHistory history = SettlementHistory.builder()
        .groupId(proposal.getGroupId())
        .proposalId(proposal.getId())
        .userId(userId)
        .actionType(SettlementHistory.ActionType.CREATED)
        .entityType(SettlementHistory.EntityType.PROPOSAL)
        .description("Settlement proposal created: " + proposal.getTitle())
        .amountCents(proposal.getTotalAmountCents())
        .currency(proposal.getCurrency())
        .status(proposal.getStatus().name())
        .metadata(String.format("{\"proposalType\":\"%s\",\"autoGenerated\":%b}", 
            proposal.getProposalType().name(), proposal.getAutoGenerated()))
        .build();

    settlementHistoryRepository.save(history);
    log.debug("Recorded proposal creation history for proposal {}", proposal.getId());
  }

  /**
   * Record settlement proposal update
   */
  public void recordProposalUpdated(SettlementProposal proposal, UUID userId) {
    SettlementHistory history = SettlementHistory.builder()
        .groupId(proposal.getGroupId())
        .proposalId(proposal.getId())
        .userId(userId)
        .actionType(SettlementHistory.ActionType.UPDATED)
        .entityType(SettlementHistory.EntityType.PROPOSAL)
        .description("Settlement proposal updated: " + proposal.getTitle())
        .amountCents(proposal.getTotalAmountCents())
        .currency(proposal.getCurrency())
        .status(proposal.getStatus().name())
        .build();

    settlementHistoryRepository.save(history);
    log.debug("Recorded proposal update history for proposal {}", proposal.getId());
  }

  /**
   * Record settlement proposal acceptance
   */
  public void recordProposalAccepted(SettlementProposal proposal, UUID userId) {
    SettlementHistory history = SettlementHistory.builder()
        .groupId(proposal.getGroupId())
        .proposalId(proposal.getId())
        .userId(userId)
        .actionType(SettlementHistory.ActionType.ACCEPTED)
        .entityType(SettlementHistory.EntityType.PROPOSAL)
        .description("Settlement proposal accepted: " + proposal.getTitle())
        .amountCents(proposal.getTotalAmountCents())
        .currency(proposal.getCurrency())
        .status(proposal.getStatus().name())
        .build();

    settlementHistoryRepository.save(history);
    log.debug("Recorded proposal acceptance history for proposal {}", proposal.getId());
  }

  /**
   * Record settlement proposal rejection
   */
  public void recordProposalRejected(SettlementProposal proposal, UUID userId) {
    SettlementHistory history = SettlementHistory.builder()
        .groupId(proposal.getGroupId())
        .proposalId(proposal.getId())
        .userId(userId)
        .actionType(SettlementHistory.ActionType.REJECTED)
        .entityType(SettlementHistory.EntityType.PROPOSAL)
        .description("Settlement proposal rejected: " + proposal.getTitle())
        .amountCents(proposal.getTotalAmountCents())
        .currency(proposal.getCurrency())
        .status(proposal.getStatus().name())
        .build();

    settlementHistoryRepository.save(history);
    log.debug("Recorded proposal rejection history for proposal {}", proposal.getId());
  }

  /**
   * Record settlement proposal completion
   */
  public void recordProposalCompleted(SettlementProposal proposal) {
    SettlementHistory history = SettlementHistory.builder()
        .groupId(proposal.getGroupId())
        .proposalId(proposal.getId())
        .userId(proposal.getProposerId())
        .actionType(SettlementHistory.ActionType.COMPLETED)
        .entityType(SettlementHistory.EntityType.PROPOSAL)
        .description("Settlement proposal completed: " + proposal.getTitle())
        .amountCents(proposal.getTotalAmountCents())
        .currency(proposal.getCurrency())
        .status(proposal.getStatus().name())
        .build();

    settlementHistoryRepository.save(history);
    log.debug("Recorded proposal completion history for proposal {}", proposal.getId());
  }

  /**
   * Record payment confirmation
   */
  public void recordPaymentConfirmed(SettlementPayment payment, UUID userId, String confirmationType) {
    SettlementHistory history = SettlementHistory.builder()
        .groupId(payment.getProposal().getGroupId())
        .proposalId(payment.getProposal().getId())
        .paymentId(payment.getId())
        .userId(userId)
        .actionType(SettlementHistory.ActionType.CONFIRMED)
        .entityType(SettlementHistory.EntityType.CONFIRMATION)
        .description(String.format("Payment confirmed by %s", confirmationType))
        .amountCents(payment.getAmountCents())
        .currency(payment.getCurrency())
        .status(payment.getStatus().name())
        .metadata(String.format("{\"confirmationType\":\"%s\",\"payerId\":\"%s\",\"payeeId\":\"%s\"}", 
            confirmationType, payment.getPayerId(), payment.getPayeeId()))
        .build();

    settlementHistoryRepository.save(history);
    log.debug("Recorded payment confirmation history for payment {}", payment.getId());
  }

  /**
   * Record payment dispute
   */
  public void recordPaymentDisputed(SettlementPayment payment, UUID userId, String reason) {
    SettlementHistory history = SettlementHistory.builder()
        .groupId(payment.getProposal().getGroupId())
        .proposalId(payment.getProposal().getId())
        .paymentId(payment.getId())
        .userId(userId)
        .actionType(SettlementHistory.ActionType.DISPUTED)
        .entityType(SettlementHistory.EntityType.DISPUTE)
        .description("Payment disputed: " + reason)
        .amountCents(payment.getAmountCents())
        .currency(payment.getCurrency())
        .status(payment.getStatus().name())
        .metadata(String.format("{\"reason\":\"%s\",\"payerId\":\"%s\",\"payeeId\":\"%s\"}", 
            reason, payment.getPayerId(), payment.getPayeeId()))
        .build();

    settlementHistoryRepository.save(history);
    log.debug("Recorded payment dispute history for payment {}", payment.getId());
  }

  /**
   * Get settlement history for a group
   */
  @Transactional(readOnly = true)
  public Page<SettlementDto.SettlementHistoryItem> getGroupSettlementHistory(
      UUID groupId, String status, Pageable pageable) {

    Page<SettlementHistory> historyPage;
    
    if (status != null && !status.trim().isEmpty()) {
      historyPage = settlementHistoryRepository.findByGroupIdAndStatusOrderByCreatedAtDesc(
          groupId, status.trim(), pageable);
    } else {
      historyPage = settlementHistoryRepository.findByGroupIdOrderByCreatedAtDesc(groupId, pageable);
    }

    return historyPage.map(this::convertToHistoryItem);
  }

  /**
   * Convert SettlementHistory entity to DTO
   */
  private SettlementDto.SettlementHistoryItem convertToHistoryItem(SettlementHistory history) {
    return SettlementDto.SettlementHistoryItem.builder()
        .id(history.getId())
        .type(history.getEntityType().name())
        .action(history.getActionType().name())
        .groupId(history.getGroupId())
        .proposalId(history.getProposalId())
        .paymentId(history.getPaymentId())
        .userId(history.getUserId())
        .description(history.getDescription())
        .amount(history.getAmountDecimal())
        .currency(history.getCurrency())
        .status(history.getStatus())
        .timestamp(history.getCreatedAt())
        .metadata(history.getMetadata())
        .build();
  }
}
