server:
  port: 8081
spring:
  application:
    name: svc-user
  datasource:
    url: jdbc:postgresql://pg-user:5432/userdb
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/expenses
management.endpoints.web.exposure.include: health,info,prometheus
