server:
  port: 8081
spring:
  application:
    name: svc-user
  datasource:
    url: jdbc:postgresql://pg-user:5432/userdb
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          # Validate JWTs using JWKS only to avoid strict issuer matching
          jwk-set-uri: http://host.docker.internal:8090/realms/expenses/protocol/openid-connect/certs
management.endpoints.web.exposure.include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    enabled: true
    groups:
      enabled: true
