package com.expenses.svcsettle.dto;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.UUID;

import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import com.expenses.svcsettle.entity.SettlementPayment;
import com.expenses.svcsettle.entity.SettlementProposal;

import lombok.Builder;

/**
 * Settlement DTOs for API communication
 */
public class SettlementDto {

  /**
   * Complete settlement proposal information
   */
  @Builder
  public record SettlementProposalResponse(
      UUID id,
      UUID groupId,
      UUID proposerId,
      String title,
      String description,
      String currency,
      BigDecimal totalAmount,
      String status,
      String proposalType,
      Boolean autoGenerated,
      ZonedDateTime expiresAt,
      ZonedDateTime createdAt,
      ZonedDateTime updatedAt,
      List<SettlementPaymentResponse> payments,
      Integer pendingPaymentsCount,
      Integer completedPaymentsCount,
      Boolean canBeModified,
      Boolean canBeAccepted,
      Boolean isExpired,
      Boolean isCompleted) {

    public static SettlementProposalResponse from(SettlementProposal proposal) {
      return SettlementProposalResponse.builder()
          .id(proposal.getId())
          .groupId(proposal.getGroupId())
          .proposerId(proposal.getProposerId())
          .title(proposal.getTitle())
          .description(proposal.getDescription())
          .currency(proposal.getCurrency())
          .totalAmount(proposal.getTotalAmountDecimal())
          .status(proposal.getStatus().name())
          .proposalType(proposal.getProposalType().name())
          .autoGenerated(proposal.getAutoGenerated())
          .expiresAt(proposal.getExpiresAt())
          .createdAt(proposal.getCreatedAt())
          .updatedAt(proposal.getUpdatedAt())
          .payments(proposal.getPayments().stream()
              .map(SettlementPaymentResponse::from)
              .toList())
          .pendingPaymentsCount(proposal.getPendingPaymentsCount())
          .completedPaymentsCount(proposal.getCompletedPaymentsCount())
          .canBeModified(proposal.canBeModified())
          .canBeAccepted(proposal.canBeAccepted())
          .isExpired(proposal.isExpired())
          .isCompleted(proposal.isCompleted())
          .build();
    }
  }

  /**
   * Create settlement proposal request
   */
  @Builder
  public record CreateSettlementProposalRequest(
      @NotNull(message = "Group ID is required") UUID groupId,

      @NotBlank(message = "Title is required") @Size(max = 200, message = "Title cannot exceed 200 characters") String title,

      @Size(max = 2000, message = "Description cannot exceed 2000 characters") String description,

      @NotBlank(message = "Currency is required") @Size(min = 3, max = 3, message = "Currency must be 3 characters") String currency,

      @NotNull(message = "Proposal type is required") SettlementProposal.ProposalType proposalType,

      @Future(message = "Expiry date must be in the future") ZonedDateTime expiresAt,

      @NotEmpty(message = "At least one payment is required") @Valid List<CreatePaymentRequest> payments) {
  }

  /**
   * Update settlement proposal request
   */
  @Builder
  public record UpdateSettlementProposalRequest(
      @NotBlank(message = "Title is required") @Size(max = 200, message = "Title cannot exceed 200 characters") String title,

      @Size(max = 2000, message = "Description cannot exceed 2000 characters") String description,

      @Future(message = "Expiry date must be in the future") ZonedDateTime expiresAt,

      @Valid List<CreatePaymentRequest> payments) {
  }

  /**
   * Settlement payment information
   */
  @Builder
  public record SettlementPaymentResponse(
      UUID id,
      UUID proposalId,
      UUID payerId,
      UUID payeeId,
      String currency,
      BigDecimal amount,
      String description,
      String status,
      String paymentMethod,
      String paymentReference,
      ZonedDateTime dueDate,
      ZonedDateTime completedAt,
      ZonedDateTime createdAt,
      ZonedDateTime updatedAt,
      List<PaymentConfirmationResponse> confirmations,
      Boolean isOverdue,
      Boolean canBeConfirmed,
      Boolean canBeCompleted,
      Boolean hasPayerConfirmation,
      Boolean hasPayeeConfirmation,
      Boolean isDisputed) {

    public static SettlementPaymentResponse from(SettlementPayment payment) {
      return SettlementPaymentResponse.builder()
          .id(payment.getId())
          .proposalId(payment.getProposal().getId())
          .payerId(payment.getPayerId())
          .payeeId(payment.getPayeeId())
          .currency(payment.getCurrency())
          .amount(payment.getAmountDecimal())
          .description(payment.getDescription())
          .status(payment.getStatus().name())
          .paymentMethod(payment.getPaymentMethod())
          .paymentReference(payment.getPaymentReference())
          .dueDate(payment.getDueDate())
          .completedAt(payment.getCompletedAt())
          .createdAt(payment.getCreatedAt())
          .updatedAt(payment.getUpdatedAt())
          .confirmations(payment.getConfirmations().stream()
              .map(PaymentConfirmationResponse::from)
              .toList())
          .isOverdue(payment.isOverdue())
          .canBeConfirmed(payment.canBeConfirmed())
          .canBeCompleted(payment.canBeCompleted())
          .hasPayerConfirmation(payment.hasPayerConfirmation())
          .hasPayeeConfirmation(payment.hasPayeeConfirmation())
          .isDisputed(payment.isDisputed())
          .build();
    }
  }

  /**
   * Create payment request
   */
  @Builder
  public record CreatePaymentRequest(
      @NotNull(message = "Payer ID is required") UUID payerId,

      @NotNull(message = "Payee ID is required") UUID payeeId,

      @NotNull(message = "Amount is required") @DecimalMin(value = "0.01", message = "Amount must be positive") BigDecimal amount,

      @Size(max = 1000, message = "Description cannot exceed 1000 characters") String description,

      @Size(max = 50, message = "Payment method cannot exceed 50 characters") String paymentMethod,

      ZonedDateTime dueDate) {
  }

  /**
   * Payment confirmation information
   */
  @Builder
  public record PaymentConfirmationResponse(
      UUID id,
      UUID paymentId,
      UUID confirmerId,
      String confirmationType,
      String notes,
      String attachmentUrl,
      ZonedDateTime createdAt) {

    public static PaymentConfirmationResponse from(com.expenses.svcsettle.entity.PaymentConfirmation confirmation) {
      return PaymentConfirmationResponse.builder()
          .id(confirmation.getId())
          .paymentId(confirmation.getPayment().getId())
          .confirmerId(confirmation.getConfirmerId())
          .confirmationType(confirmation.getConfirmationType().name())
          .notes(confirmation.getNotes())
          .attachmentUrl(confirmation.getAttachmentUrl())
          .createdAt(confirmation.getCreatedAt())
          .build();
    }
  }

  /**
   * Payment confirmation request
   */
  @Builder
  public record PaymentConfirmationRequest(
      @Size(max = 2000, message = "Notes cannot exceed 2000 characters") String notes,

      @Size(max = 500, message = "Attachment URL cannot exceed 500 characters") String attachmentUrl,

      @Size(max = 100, message = "Payment reference cannot exceed 100 characters") String paymentReference) {
  }

  /**
   * Dispute payment request
   */
  @Builder
  public record DisputePaymentRequest(
      @NotBlank(message = "Reason is required") @Size(max = 2000, message = "Reason cannot exceed 2000 characters") String reason,

      @Size(max = 500, message = "Attachment URL cannot exceed 500 characters") String attachmentUrl) {
  }

  /**
   * Settlement proposal summary for lists
   */
  @Builder
  public record SettlementProposalSummary(
      UUID id,
      UUID groupId,
      UUID proposerId,
      String title,
      String currency,
      BigDecimal totalAmount,
      String status,
      String proposalType,
      Boolean autoGenerated,
      Integer paymentsCount,
      Integer completedPaymentsCount,
      ZonedDateTime expiresAt,
      ZonedDateTime createdAt) {

    public static SettlementProposalSummary from(SettlementProposal proposal) {
      return SettlementProposalSummary.builder()
          .id(proposal.getId())
          .groupId(proposal.getGroupId())
          .proposerId(proposal.getProposerId())
          .title(proposal.getTitle())
          .currency(proposal.getCurrency())
          .totalAmount(proposal.getTotalAmountDecimal())
          .status(proposal.getStatus().name())
          .proposalType(proposal.getProposalType().name())
          .autoGenerated(proposal.getAutoGenerated())
          .paymentsCount(proposal.getPayments().size())
          .completedPaymentsCount(proposal.getCompletedPaymentsCount())
          .expiresAt(proposal.getExpiresAt())
          .createdAt(proposal.getCreatedAt())
          .build();
    }
  }

  /**
   * Debt optimization request
   */
  @Builder
  public record DebtOptimizationRequest(
      @NotNull(message = "Group ID is required") UUID groupId,

      @NotBlank(message = "Currency is required") @Size(min = 3, max = 3, message = "Currency must be 3 characters") String currency,

      @DecimalMin(value = "0.01", message = "Minimum amount must be positive") BigDecimal minimumAmount,

      Boolean createProposal) {
  }

  /**
   * Debt optimization result
   */
  @Builder
  public record DebtOptimizationResult(
      UUID groupId,
      String currency,
      BigDecimal totalDebtAmount,
      Integer originalTransactionsCount,
      Integer optimizedTransactionsCount,
      BigDecimal savingsPercentage,
      List<OptimizedTransaction> optimizedTransactions,
      UUID proposalId // If proposal was created
  ) {
  }

  /**
   * Optimized transaction in debt simplification
   */
  @Builder
  public record OptimizedTransaction(
      UUID payerId,
      UUID payeeId,
      BigDecimal amount,
      String description) {
  }

  /**
   * Group settlement status and debt summary
   */
  @Builder
  public record GroupSettlementStatus(
      UUID groupId,
      String currency,
      BigDecimal totalDebtAmount,
      BigDecimal totalSettledAmount,
      BigDecimal remainingDebtAmount,
      Integer activeProposalsCount,
      Integer completedProposalsCount,
      Integer pendingPaymentsCount,
      Integer completedPaymentsCount,
      Integer disputedPaymentsCount,
      List<DebtSummary> debtSummary,
      List<SettlementProposalSummary> activeProposals,
      ZonedDateTime lastSettlementAt,
      ZonedDateTime calculatedAt) {
  }

  /**
   * Debt summary for a user in a group
   */
  @Builder
  public record DebtSummary(
      UUID userId,
      BigDecimal totalOwed,
      BigDecimal totalOwing,
      BigDecimal netBalance,
      Integer activeDebtsCount,
      Integer activeCreditsCount) {
  }

  /**
   * Settlement history item for audit trail
   */
  @Builder
  public record SettlementHistoryItem(
      UUID id,
      String type, // "PROPOSAL", "PAYMENT", "CONFIRMATION", "DISPUTE"
      String action, // "CREATED", "ACCEPTED", "REJECTED", "COMPLETED", "CONFIRMED", "DISPUTED"
      UUID groupId,
      UUID proposalId,
      UUID paymentId,
      UUID userId,
      String description,
      BigDecimal amount,
      String currency,
      String status,
      ZonedDateTime timestamp,
      String metadata) {
  }
}
