plugins {
  id 'java-library'
  alias(libs.plugins.depman)
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}"
    }
}

dependencies {
  api 'org.springframework.kafka:spring-kafka'
  api 'org.springframework:spring-context'
  api 'org.springframework:spring-messaging'
  api 'com.fasterxml.jackson.core:jackson-annotations'
  api 'com.fasterxml.jackson.core:jackson-databind'
  
  compileOnly libs.lombok
  annotationProcessor libs.lombok
  
  implementation 'org.slf4j:slf4j-api'
  implementation libs.spring.boot.starter.validation
  
  testImplementation libs.junit.jupiter
  testCompileOnly libs.lombok
  testAnnotationProcessor libs.lombok
}