package com.expenses.svcsettle.repository;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.expenses.svcsettle.entity.SettlementProposal;

@Repository
public interface SettlementProposalRepository extends JpaRepository<SettlementProposal, UUID> {

  /**
   * Find proposals by group ID
   */
  Page<SettlementProposal> findByGroupIdOrderByCreatedAtDesc(UUID groupId, Pageable pageable);

  /**
   * Find proposals by proposer ID
   */
  Page<SettlementProposal> findByProposerIdOrderByCreatedAtDesc(UUID proposerId, Pageable pageable);

  /**
   * Find proposals by status
   */
  Page<SettlementProposal> findByStatusOrderByCreatedAtDesc(SettlementProposal.SettlementStatus status,
      Pageable pageable);

  /**
   * Find proposals by group and status
   */
  Page<SettlementProposal> findByGroupIdAndStatusOrderByCreatedAtDesc(
      UUID groupId, SettlementProposal.SettlementStatus status, Pageable pageable);

  /**
   * Find expired proposals that are still pending
   */
  @Query("SELECT sp FROM SettlementProposal sp WHERE sp.status = 'PENDING' " +
      "AND sp.expiresAt IS NOT NULL AND sp.expiresAt < :now")
  List<SettlementProposal> findExpiredPendingProposals(@Param("now") ZonedDateTime now);

  /**
   * Find auto-generated proposals by group
   */
  List<SettlementProposal> findByGroupIdAndAutoGeneratedTrueOrderByCreatedAtDesc(UUID groupId);

  /**
   * Find proposals where user is involved (as proposer or in payments)
   */
  @Query("SELECT DISTINCT sp FROM SettlementProposal sp " +
      "LEFT JOIN sp.payments p " +
      "WHERE sp.proposerId = :userId OR p.payerId = :userId OR p.payeeId = :userId " +
      "ORDER BY sp.createdAt DESC")
  Page<SettlementProposal> findByUserInvolvement(@Param("userId") UUID userId, Pageable pageable);

  /**
   * Find proposals where user is involved in specific group
   */
  @Query("SELECT DISTINCT sp FROM SettlementProposal sp " +
      "LEFT JOIN sp.payments p " +
      "WHERE sp.groupId = :groupId AND " +
      "(sp.proposerId = :userId OR p.payerId = :userId OR p.payeeId = :userId) " +
      "ORDER BY sp.createdAt DESC")
  Page<SettlementProposal> findByGroupAndUserInvolvement(
      @Param("groupId") UUID groupId, @Param("userId") UUID userId, Pageable pageable);

  /**
   * Count proposals by group and status
   */
  Long countByGroupIdAndStatus(UUID groupId, SettlementProposal.SettlementStatus status);

  /**
   * Find proposals with pending payments for a user
   */
  @Query("SELECT DISTINCT sp FROM SettlementProposal sp " +
      "JOIN sp.payments p " +
      "WHERE (p.payerId = :userId OR p.payeeId = :userId) " +
      "AND p.status IN ('PENDING', 'CONFIRMED') " +
      "AND sp.status = 'ACCEPTED' " +
      "ORDER BY p.dueDate ASC NULLS LAST, sp.createdAt DESC")
  Page<SettlementProposal> findProposalsWithPendingPaymentsForUser(
      @Param("userId") UUID userId, Pageable pageable);

  /**
   * Find overdue payments for notifications
   */
  @Query("SELECT DISTINCT sp FROM SettlementProposal sp " +
      "JOIN sp.payments p " +
      "WHERE p.dueDate < :now " +
      "AND p.status IN ('PENDING', 'CONFIRMED') " +
      "AND sp.status = 'ACCEPTED'")
  List<SettlementProposal> findProposalsWithOverduePayments(@Param("now") ZonedDateTime now);

  /**
   * Update expired proposals status
   */
  @Modifying
  @Query("UPDATE SettlementProposal sp SET sp.status = 'EXPIRED' " +
      "WHERE sp.status = 'PENDING' AND sp.expiresAt IS NOT NULL AND sp.expiresAt < :now")
  int markExpiredProposalsAsExpired(@Param("now") ZonedDateTime now);

  /**
   * Search proposals by title or description
   */
  @Query("SELECT sp FROM SettlementProposal sp WHERE sp.groupId = :groupId " +
      "AND (LOWER(sp.title) LIKE LOWER(CONCAT('%', :query, '%')) " +
      "OR LOWER(sp.description) LIKE LOWER(CONCAT('%', :query, '%'))) " +
      "ORDER BY sp.createdAt DESC")
  Page<SettlementProposal> searchInGroup(@Param("query") String query,
      @Param("groupId") UUID groupId,
      Pageable pageable);

  /**
   * Get settlement statistics for a group
   */
  @Query("SELECT " +
      "COUNT(sp), " +
      "COUNT(CASE WHEN sp.status = 'COMPLETED' THEN 1 END), " +
      "COUNT(CASE WHEN sp.status = 'PENDING' THEN 1 END), " +
      "COALESCE(SUM(CASE WHEN sp.status = 'COMPLETED' THEN sp.totalAmountCents ELSE 0 END), 0) " +
      "FROM SettlementProposal sp WHERE sp.groupId = :groupId")
  Object[] getGroupSettlementStatistics(@Param("groupId") UUID groupId);

  /**
   * Find recent completed settlements for a group
   */
  @Query("SELECT sp FROM SettlementProposal sp WHERE sp.groupId = :groupId " +
      "AND sp.status = 'COMPLETED' " +
      "ORDER BY sp.updatedAt DESC")
  Page<SettlementProposal> findRecentCompletedSettlements(@Param("groupId") UUID groupId, Pageable pageable);

  /**
   * Check if user has permission to access proposal
   */
  @Query("SELECT COUNT(sp) > 0 FROM SettlementProposal sp " +
      "LEFT JOIN sp.payments p " +
      "WHERE sp.id = :proposalId AND " +
      "(sp.proposerId = :userId OR p.payerId = :userId OR p.payeeId = :userId)")
  boolean hasUserAccess(@Param("proposalId") UUID proposalId, @Param("userId") UUID userId);

  /**
   * Find proposals that can be auto-completed
   */
  @Query("SELECT sp FROM SettlementProposal sp WHERE sp.status = 'ACCEPTED' " +
      "AND NOT EXISTS (SELECT p FROM sp.payments p WHERE p.status != 'COMPLETED')")
  List<SettlementProposal> findProposalsReadyForCompletion();
}
