package com.expenses.svcsettle.entity;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Entity
@Table(name = "settlement_proposals")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
@ToString(exclude = "payments")
public class SettlementProposal {

  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  @Column(name = "group_id", nullable = false)
  @NotNull(message = "Group ID is required")
  private UUID groupId;

  @Column(name = "proposer_id", nullable = false)
  @NotNull(message = "Proposer ID is required")
  private UUID proposerId;

  @Column(nullable = false)
  @NotBlank(message = "Title is required")
  @Size(max = 200, message = "Title cannot exceed 200 characters")
  private String title;

  @Column(columnDefinition = "TEXT")
  @Size(max = 2000, message = "Description cannot exceed 2000 characters")
  private String description;

  @Column(length = 3, nullable = false)
  @NotBlank(message = "Currency is required")
  @Size(min = 3, max = 3, message = "Currency must be 3 characters")
  private String currency;

  @Column(name = "total_amount_cents", nullable = false)
  @Positive(message = "Total amount must be positive")
  @Builder.Default
  private Long totalAmountCents = 0L;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  @Builder.Default
  private SettlementStatus status = SettlementStatus.PENDING;

  @Enumerated(EnumType.STRING)
  @Column(name = "proposal_type", nullable = false)
  @Builder.Default
  private ProposalType proposalType = ProposalType.DEBT_SIMPLIFICATION;

  @Column(name = "auto_generated", nullable = false)
  @Builder.Default
  private Boolean autoGenerated = false;

  @Column(name = "expires_at")
  private ZonedDateTime expiresAt;

  @CreationTimestamp
  @Column(name = "created_at", nullable = false, updatable = false)
  private ZonedDateTime createdAt;

  @UpdateTimestamp
  @Column(name = "updated_at", nullable = false)
  private ZonedDateTime updatedAt;

  @OneToMany(mappedBy = "proposal", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  @Builder.Default
  private List<SettlementPayment> payments = new ArrayList<>();

  // Enums
  public enum SettlementStatus {
    PENDING,
    ACCEPTED,
    REJECTED,
    EXPIRED,
    COMPLETED,
    CANCELLED
  }

  public enum ProposalType {
    DEBT_SIMPLIFICATION, // Auto-generated debt optimization
    MANUAL_SETTLEMENT, // User-created settlement
    GROUP_BALANCE, // Balance entire group
    PARTIAL_PAYMENT // Partial debt settlement
  }

  // Helper methods
  public BigDecimal getTotalAmountDecimal() {
    return BigDecimal.valueOf(totalAmountCents, 2);
  }

  public void setTotalAmountDecimal(BigDecimal amount) {
    this.totalAmountCents = amount.movePointRight(2).longValue();
  }

  public void addPayment(SettlementPayment payment) {
    payments.add(payment);
    payment.setProposal(this);
  }

  public void removePayment(SettlementPayment payment) {
    payments.remove(payment);
    payment.setProposal(null);
  }

  public boolean isExpired() {
    return expiresAt != null && ZonedDateTime.now().isAfter(expiresAt);
  }

  public boolean canBeModified() {
    return status == SettlementStatus.PENDING && !isExpired();
  }

  public boolean canBeAccepted() {
    return status == SettlementStatus.PENDING && !isExpired() && !payments.isEmpty();
  }

  public boolean isCompleted() {
    return status == SettlementStatus.COMPLETED ||
        (status == SettlementStatus.ACCEPTED &&
            payments.stream().allMatch(p -> p.getStatus() == SettlementPayment.PaymentStatus.COMPLETED));
  }

  public int getPendingPaymentsCount() {
    return (int) payments.stream()
        .filter(p -> p.getStatus() == SettlementPayment.PaymentStatus.PENDING ||
            p.getStatus() == SettlementPayment.PaymentStatus.CONFIRMED)
        .count();
  }

  public int getCompletedPaymentsCount() {
    return (int) payments.stream()
        .filter(p -> p.getStatus() == SettlementPayment.PaymentStatus.COMPLETED)
        .count();
  }

  @PrePersist
  @PreUpdate
  private void calculateTotalAmount() {
    this.totalAmountCents = payments.stream()
        .mapToLong(SettlementPayment::getAmountCents)
        .sum();
  }

  public void markAsExpired() {
    if (canBeModified() && isExpired()) {
      this.status = SettlementStatus.EXPIRED;
    }
  }

  public void accept() {
    if (canBeAccepted()) {
      this.status = SettlementStatus.ACCEPTED;
    } else {
      throw new IllegalStateException("Settlement proposal cannot be accepted in current state");
    }
  }

  public void reject() {
    if (status == SettlementStatus.PENDING) {
      this.status = SettlementStatus.REJECTED;
    } else {
      throw new IllegalStateException("Only pending proposals can be rejected");
    }
  }

  public void cancel() {
    if (status == SettlementStatus.PENDING || status == SettlementStatus.ACCEPTED) {
      this.status = SettlementStatus.CANCELLED;
    } else {
      throw new IllegalStateException("Cannot cancel proposal in current state");
    }
  }

  public void complete() {
    if (status == SettlementStatus.ACCEPTED && isCompleted()) {
      this.status = SettlementStatus.COMPLETED;
    }
  }
}
