plugins {
  alias(libs.plugins.spring.boot)
}

dependencies {
  implementation(libs.spring.boot.starter.web)
  implementation(libs.spring.boot.starter.actuator)
  implementation(libs.springdoc.openapi.starter)
  implementation(libs.spring.boot.starter.security)
  implementation(libs.spring.boot.starter.oauth2.resource.server)
  implementation(libs.spring.boot.starter.data.jpa)
  implementation(libs.spring.boot.starter.validation)
  implementation(libs.postgres)
  implementation(libs.flyway)
  implementation(libs.flyway.database.postgresql)
  implementation(libs.spring.kafka)
  implementation(libs.commons.lang3)
  
  // Common library for events
  implementation project(':libs:common')
  
  compileOnly(libs.lombok)
  annotationProcessor(libs.lombok)

  testImplementation(libs.spring.boot.starter.test)
  testCompileOnly(libs.lombok)
  testAnnotationProcessor(libs.lombok)
}
